//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AMS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji mungesës.
        /// </summary>
        public static string AbsentType {
            get {
                return ResourceManager.GetString("AbsentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja u ndryshua me sukses!.
        /// </summary>
        public static string AccessChangedSuccessfully {
            get {
                return ResourceManager.GetString("AccessChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja është e ndaluar!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria është krijuar me sukses!.
        /// </summary>
        public static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat e llogarisë.
        /// </summary>
        public static string AccountData {
            get {
                return ResourceManager.GetString("AccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria është bllokuar!.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria u bllokuar me sukses.
        /// </summary>
        public static string AccountLockedSuccess {
            get {
                return ResourceManager.GetString("AccountLockedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria nuk mund të bllokohet.
        /// </summary>
        public static string AccountNotLocked {
            get {
                return ResourceManager.GetString("AccountNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria nuk mund të zhbllokohet.
        /// </summary>
        public static string AccountNotUnlocked {
            get {
                return ResourceManager.GetString("AccountNotUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria u zhbllokuar me sukses.
        /// </summary>
        public static string AccountUnlockedSuccess {
            get {
                return ResourceManager.GetString("AccountUnlockedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veprimet.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto departament.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto dokument.
        /// </summary>
        public static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto meny.
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto grupin.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto grupin - {0}.
        /// </summary>
        public static string AddRoleFor {
            get {
                return ResourceManager.GetString("AddRoleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto nënmeny.
        /// </summary>
        public static string AddSubMenu {
            get {
                return ResourceManager.GetString("AddSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto nënmeny - {0}.
        /// </summary>
        public static string AddSubMenuFor {
            get {
                return ResourceManager.GetString("AddSubMenuFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto përdoruesin.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQ.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqip.
        /// </summary>
        public static string Albanian {
            get {
                return ResourceManager.GetString("Albanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatet e lejuara janë: {0}.
        /// </summary>
        public static string AllowedFileFormats {
            get {
                return ResourceManager.GetString("AllowedFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatet e lejuara për foto.
        /// </summary>
        public static string AllowedFormatImage {
            get {
                return ResourceManager.GetString("AllowedFormatImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të gjitha të drejtat e rezervuara.
        /// </summary>
        public static string AllRightReserved {
            get {
                return ResourceManager.GetString("AllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemi për menaxhimin e pjesmarrjes.
        /// </summary>
        public static string AMS {
            get {
                return ResourceManager.GetString("AMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistemi për Menaxhimin e Pjesëmarrjes.
        /// </summary>
        public static string AMSTitle {
            get {
                return ResourceManager.GetString("AMSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrat e aplikacionit.
        /// </summary>
        public static string ApplicationSetings {
            get {
                return ResourceManager.GetString("ApplicationSetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni të sigurt?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me llogari tjetër.
        /// </summary>
        public static string AsDiffUser {
            get {
                return ResourceManager.GetString("AsDiffUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pjesëmarrja.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pjesëmarrja u ndryshua me sukses.
        /// </summary>
        public static string AttendanceChangedSuccessfully {
            get {
                return ResourceManager.GetString("AttendanceChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia e pjesëmarrjes.
        /// </summary>
        public static string AttendanceHistory {
            get {
                return ResourceManager.GetString("AttendanceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e pjesëmarrjes.
        /// </summary>
        public static string AttendanceList {
            get {
                return ResourceManager.GetString("AttendanceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimi.
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimet.
        /// </summary>
        public static string Authorizations {
            get {
                return ResourceManager.GetString("Authorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimet për veprimet në sistem.
        /// </summary>
        public static string AuthorizationsForActions {
            get {
                return ResourceManager.GetString("AuthorizationsForActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizimet për menytë.
        /// </summary>
        public static string AuthorizationsForMenus {
            get {
                return ResourceManager.GetString("AuthorizationsForMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prapa.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka munguar.
        /// </summary>
        public static string BeenAbsent {
            get {
                return ResourceManager.GetString("BeenAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e lindjes.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngarko.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulo.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho grupin.
        /// </summary>
        public static string ChangeRole {
            get {
                return ResourceManager.GetString("ChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duhet të ketë të paktën {2} dhe maksimumi {1} karaktere..
        /// </summary>
        public static string CharacterLength {
            get {
                return ResourceManager.GetString("CharacterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedh.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qyteti.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlera autorizimit.
        /// </summary>
        public static string ClaimPolicy {
            get {
                return ResourceManager.GetString("ClaimPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastro.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyll.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përfunduar.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin e ri.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfirmo fjalëkalimin.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radhazi.
        /// </summary>
        public static string Consecutive {
            get {
                return ResourceManager.GetString("Consecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditë të njëpasnjëshme.
        /// </summary>
        public static string ConsecutiveDays {
            get {
                return ResourceManager.GetString("ConsecutiveDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vazhdo.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrolleri.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk mund të shtoheshin grupet për llogarinë e krijuar të stafit. Grupet mund t&apos;i shtoni në listën e përdorusve..
        /// </summary>
        public static string CouldNotAddRole {
            get {
                return ResourceManager.GetString("CouldNotAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri gjurmëve sot.
        /// </summary>
        public static string CountOfLogsToday {
            get {
                return ResourceManager.GetString("CountOfLogsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri përdoruesve.
        /// </summary>
        public static string CountOfUsers {
            get {
                return ResourceManager.GetString("CountOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shteti.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errët.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u fshinë me sukses!.
        /// </summary>
        public static string DataDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DataDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u regjistruan me sukses!.
        /// </summary>
        public static string DataRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("DataRegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat u ndryshuan me sukses!.
        /// </summary>
        public static string DataUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DataUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditë.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditë më parë.
        /// </summary>
        public static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditë.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditë më parë.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamenti.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përshkrimi.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detajet.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhvilluar nga.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhvilluesi.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenti.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madhësia maksimale e dokumentit.
        /// </summary>
        public static string DocumentMaxFileSize {
            get {
                return ResourceManager.GetString("DocumentMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumente.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji dokumentit.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkarko.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho dokumentin.
        /// </summary>
        public static string EditDocument {
            get {
                return ResourceManager.GetString("EditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurimi i e-mailit.
        /// </summary>
        public static string EmailConfiguration {
            get {
                return ResourceManager.GetString("EmailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-maili ekziston!.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-maili nuk është valid!.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AN.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përfundo.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data mbarimit.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglisht.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim gjatë procesimit të të dhënave! Ju lutem provoni përsëri më vonë..
        /// </summary>
        public static string ErrorProcessingData {
            get {
                return ResourceManager.GetString("ErrorProcessingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ekziston si {2}. Duhet të pasivizoni këtë për të regjistruar pastaj!.
        /// </summary>
        public static string ExistsStaffRole {
            get {
                return ResourceManager.GetString("ExistsStaffRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femër.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusha.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Të dhënat personale.
        /// </summary>
        public static string FirstStepStaffRegistration {
            get {
                return ResourceManager.GetString("FirstStepStaffRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Për.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keni harruar fjalëkalimin?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjinia.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shko në ballinë.
        /// </summary>
        public static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka.
        /// </summary>
        public static string Has {
            get {
                return ResourceManager.GetString("Has", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka qasje.
        /// </summary>
        public static string HasAccess {
            get {
                return ResourceManager.GetString("HasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka nënmeny.
        /// </summary>
        public static string HasSubMenu {
            get {
                return ResourceManager.GetString("HasSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tung.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballina.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orë.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orë më parë.
        /// </summary>
        public static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orë.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orë më parë.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikona.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto u ndryshua me sukses!.
        /// </summary>
        public static string ImageChangedSuccess {
            get {
                return ResourceManager.GetString("ImageChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i pasaktë!.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkruani email-in tuaj për të dërguar linkun për ndryshimin e fjalëkalimit.
        /// </summary>
        public static string InputEmailToResetPassword {
            get {
                return ResourceManager.GetString("InputEmailToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e insertimit.
        /// </summary>
        public static string InsertedDate {
            get {
                return ResourceManager.GetString("InsertedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat nuk janë valide!.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/emri përdoruesit ose fjalëkalimi janë të pasakta!.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qelësi.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjuha.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndriçuar.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e parametrave të aplikacionit.
        /// </summary>
        public static string ListOfAppSettings {
            get {
                return ResourceManager.GetString("ListOfAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e departamenteve.
        /// </summary>
        public static string ListOfDepartments {
            get {
                return ResourceManager.GetString("ListOfDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e gjurmëve.
        /// </summary>
        public static string ListOfLogs {
            get {
                return ResourceManager.GetString("ListOfLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e menyve.
        /// </summary>
        public static string ListOfMenus {
            get {
                return ResourceManager.GetString("ListOfMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista njoftimeve.
        /// </summary>
        public static string ListOfNotifications {
            get {
                return ResourceManager.GetString("ListOfNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e stafit në proces të regjistrimit.
        /// </summary>
        public static string ListOfStaffInProcessRegistration {
            get {
                return ResourceManager.GetString("ListOfStaffInProcessRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista e nënmenyve.
        /// </summary>
        public static string ListSubMenus {
            get {
                return ResourceManager.GetString("ListSubMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiko më shumë.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blloko llogarinë.
        /// </summary>
        public static string LockAccount {
            get {
                return ResourceManager.GetString("LockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bllokuar.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçu.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçuni?.
        /// </summary>
        public static string LoginInstead {
            get {
                return ResourceManager.GetString("LoginInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyçuni për të filluar sesionin tuaj..
        /// </summary>
        public static string LoginToStart {
            get {
                return ResourceManager.GetString("LoginToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkyçu.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiko më pak.
        /// </summary>
        public static string LookLess {
            get {
                return ResourceManager.GetString("LookLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiko më shumë.
        /// </summary>
        public static string LookMore {
            get {
                return ResourceManager.GetString("LookMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelat ndihmëse.
        /// </summary>
        public static string LookUpTables {
            get {
                return ResourceManager.GetString("LookUpTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashkull.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shëno si të lexuar.
        /// </summary>
        public static string MarkAsRead {
            get {
                return ResourceManager.GetString("MarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjatësia maksimale e shkronjave është 10..
        /// </summary>
        public static string MaxChar10 {
            get {
                return ResourceManager.GetString("MaxChar10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madhësia maksimale e lejuar për foto.
        /// </summary>
        public static string MaxImageSize {
            get {
                return ResourceManager.GetString("MaxImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meny.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri menysë.
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menytë dhe nënmenytë.
        /// </summary>
        public static string MenuSubmenu {
            get {
                return ResourceManager.GetString("MenuSubmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metoda.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjatësia minimale e shkronjave është 10..
        /// </summary>
        public static string MinChar10 {
            get {
                return ResourceManager.GetString("MinChar10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutë.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutë më parë.
        /// </summary>
        public static string MinuteAgo {
            get {
                return ResourceManager.GetString("MinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta më parë.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punonjësi i stafit duhet të jetë 18 vjeç ose më i vjetër..
        /// </summary>
        public static string MustBe18YearsOld {
            get {
                return ResourceManager.GetString("MustBe18YearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri anglisht.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri shqip.
        /// </summary>
        public static string NameSq {
            get {
                return ResourceManager.GetString("NameSq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdorues të ri.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jo.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk ka dokumente.
        /// </summary>
        public static string NoDocuments {
            get {
                return ResourceManager.GetString("NoDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk u gjetë rezultate!.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri normalizuar.
        /// </summary>
        public static string NormalizedName {
            get {
                return ResourceManager.GetString("NormalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk lejohet data më e madhe se sot!.
        /// </summary>
        public static string NotAllowedGreaterDate {
            get {
                return ResourceManager.GetString("NotAllowedGreaterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Njoftimet.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri pjesëmarrjes.
        /// </summary>
        public static string NumberOfAttendance {
            get {
                return ResourceManager.GetString("NumberOfAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri pjesëmarrjes sipas ditëve.
        /// </summary>
        public static string NumberOfAttendanceByDate {
            get {
                return ResourceManager.GetString("NumberOfAttendanceByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri pjesëmarrjes sipas ditëve për një javë.
        /// </summary>
        public static string NumberOfAttendanceByDateForWeek {
            get {
                return ResourceManager.GetString("NumberOfAttendanceByDateForWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri pjesëmarrjes sot.
        /// </summary>
        public static string NumberOfAttendanceToday {
            get {
                return ResourceManager.GetString("NumberOfAttendanceToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri dokumenteve.
        /// </summary>
        public static string NumberOfDocuments {
            get {
                return ResourceManager.GetString("NumberOfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri stafit.
        /// </summary>
        public static string NumberOfStaff {
            get {
                return ResourceManager.GetString("NumberOfStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri përdoruesve.
        /// </summary>
        public static string NumberOfUsers {
            get {
                return ResourceManager.GetString("NumberOfUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri përdoruesve sipas grupeve.
        /// </summary>
        public static string NumberOfUsersByGroups {
            get {
                return ResourceManager.GetString("NumberOfUsersByGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JO.
        /// </summary>
        public static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        public static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetëm numra.
        /// </summary>
        public static string OnlyNumbers {
            get {
                return ResourceManager.GetString("OnlyNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapur për.
        /// </summary>
        public static string OpenFor {
            get {
                return ResourceManager.GetString("OpenFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri rendor.
        /// </summary>
        public static string OrdinalNumber {
            get {
                return ResourceManager.GetString("OrdinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasive.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi nuk mund të vendoset.
        /// </summary>
        public static string PasswordNotAdded {
            get {
                return ResourceManager.GetString("PasswordNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimet nuk përputhen!.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi u ndryshua me sukses!.
        /// </summary>
        public static string PasswordUpdatedSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat personale.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri personal.
        /// </summary>
        public static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri telefonit.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutem provoni përsëri më vonë!.
        /// </summary>
        public static string PleaseTryAgainLater {
            get {
                return ResourceManager.GetString("PleaseTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutem prisni....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi postal.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto profilit.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regjistro.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largo.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo fushë është obligative!.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthe.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rikthe fjalëkalimin.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi u shtua me sukses!.
        /// </summary>
        public static string RoleAddedSuccess {
            get {
                return ResourceManager.GetString("RoleAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi u ndryshua me sukses!.
        /// </summary>
        public static string RoleChangedSuccess {
            get {
                return ResourceManager.GetString("RoleChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupi ekziston!.
        /// </summary>
        public static string RoleExists {
            get {
                return ResourceManager.GetString("RoleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupet.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupet mund t&apos;i shtoni edhe nga lista e përdoruesve!.
        /// </summary>
        public static string RolesAddThroughList {
            get {
                return ResourceManager.GetString("RolesAddThroughList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruaj.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërko.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkoni sipas parametrave.
        /// </summary>
        public static string SearchByCriteria {
            get {
                return ResourceManager.GetString("SearchByCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke kërkuar....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrat e kërkimit.
        /// </summary>
        public static string SearchParameters {
            get {
                return ResourceManager.GetString("SearchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultati kërkimit.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekondë.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekondë më parë.
        /// </summary>
        public static string SecondAgo {
            get {
                return ResourceManager.GetString("SecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekonda.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekonda më parë.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Dokumentet.
        /// </summary>
        public static string SecondStepStaffRegistration {
            get {
                return ResourceManager.GetString("SecondStepStaffRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dërgo email-in.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesioni ka mbaruar.
        /// </summary>
        public static string SessionTimedOut {
            get {
                return ResourceManager.GetString("SessionTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendos.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendos fjalëkalimin.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendos fjalëkalimin - {0}.
        /// </summary>
        public static string SetPasswordFor {
            get {
                return ResourceManager.GetString("SetPasswordFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiko nënmenytë.
        /// </summary>
        public static string ShowSubMenus {
            get {
                return ResourceManager.GetString("ShowSubMenus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ekziston me grupin e selektuar!.
        /// </summary>
        public static string StaffExistsWithRole {
            get {
                return ResourceManager.GetString("StaffExistsWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista stafit.
        /// </summary>
        public static string StaffList {
            get {
                return ResourceManager.GetString("StaffList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi nuk është regjistruar në një departament. Dëshironi të vazhdoni?.
        /// </summary>
        public static string StaffNotComplete {
            get {
                return ResourceManager.GetString("StaffNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji stafit.
        /// </summary>
        public static string StaffType {
            get {
                return ResourceManager.GetString("StaffType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stafi me numrin personal të dhënë ekziston!.
        /// </summary>
        public static string StaffWithPersonalExists {
            get {
                return ResourceManager.GetString("StaffWithPersonalExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fillimit.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data e fillimit nuk mund të jetë më e madhe se data e mbarimit!.
        /// </summary>
        public static string StartDateVSEndDate {
            get {
                return ResourceManager.GetString("StartDateVSEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjendja.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji statusit.
        /// </summary>
        public static string StatusType {
            get {
                return ResourceManager.GetString("StatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nënmeny.
        /// </summary>
        public static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulli nënmenysë.
        /// </summary>
        public static string SubMenuTitle {
            get {
                return ResourceManager.GetString("SubMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukses.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e departamentit nga stafi?.
        /// </summary>
        public static string SureYouWantToDeleteDepartmentForStaff {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteDepartmentForStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e dokumentit?.
        /// </summary>
        public static string SureYouWantToDeleteDocument {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e menysë?.
        /// </summary>
        public static string SureYouWantToDeleteMenu {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e grupit?.
        /// </summary>
        public static string SureYouWantToDeleteRole {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e stafit?.
        /// </summary>
        public static string SureYouWantToDeleteStaff {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e nënmenysë?.
        /// </summary>
        public static string SureYouWantToDeleteSubMenu {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për fshirjen e përdoruesit?.
        /// </summary>
        public static string SureYouWantToDeleteUser {
            get {
                return ResourceManager.GetString("SureYouWantToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për bllokimin e përdoruesit?.
        /// </summary>
        public static string SureYouWantToLockUser {
            get {
                return ResourceManager.GetString("SureYouWantToLockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt për zhbllokimin e përdoruesit?.
        /// </summary>
        public static string SureYouWantToUnlockUser {
            get {
                return ResourceManager.GetString("SureYouWantToUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gabim në sistem!.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabelat.
        /// </summary>
        public static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim në sistem..
        /// </summary>
        public static string ThereHasBeenSystemError {
            get {
                return ResourceManager.GetString("ThereHasBeenSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim. Provoni përsëri më vonë!.
        /// </summary>
        public static string ThereWasAnError {
            get {
                return ResourceManager.GetString("ThereWasAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Departamenti.
        /// </summary>
        public static string ThirdStepStaffRegistration {
            get {
                return ResourceManager.GetString("ThirdStepStaffRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjo llogari është bllokuar!.
        /// </summary>
        public static string ThisAccountLocked {
            get {
                return ResourceManager.GetString("ThisAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulli.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lloji.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shkruaj fjalëkalimin për të rikthyer sesionin.
        /// </summary>
        public static string TypePasswordToSession {
            get {
                return ResourceManager.GetString("TypePasswordToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E pamundur të ngarkohet përdoruesi..
        /// </summary>
        public static string UnableToLoadUser {
            get {
                return ResourceManager.GetString("UnableToLoadUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhblloko llogarinë.
        /// </summary>
        public static string UnlockAccount {
            get {
                return ResourceManager.GetString("UnlockAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho të dhënat e llogarisë.
        /// </summary>
        public static string UpdateAccountData {
            get {
                return ResourceManager.GetString("UpdateAccountData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi juaj u ndryshua me sukses!.
        /// </summary>
        public static string UpdatedPassword {
            get {
                return ResourceManager.GetString("UpdatedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profili juaj u ndryshua me sukses!.
        /// </summary>
        public static string UpdatedProfile {
            get {
                return ResourceManager.GetString("UpdatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho foton.
        /// </summary>
        public static string UpdateImage {
            get {
                return ResourceManager.GetString("UpdateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndrysho fjalëkalimin.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshoni të dhënat personale.
        /// </summary>
        public static string UpdatePersonalData {
            get {
                return ResourceManager.GetString("UpdatePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky përdorues ka llogari!.
        /// </summary>
        public static string UserHasAccount {
            get {
                return ResourceManager.GetString("UserHasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri përdoruesit.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri përdoruesit ekziston!.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesit.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlera.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kujdes.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke punuar që.
        /// </summary>
        public static string WorkingSince {
            get {
                return ResourceManager.GetString("WorkingSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk keni qasje në këtë pjesë të sistemit!.
        /// </summary>
        public static string YouHaveNoAccessHere {
            get {
                return ResourceManager.GetString("YouHaveNoAccessHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk keni njoftime.
        /// </summary>
        public static string YouHaveNoNotifications {
            get {
                return ResourceManager.GetString("YouHaveNoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duhet të konfirmoni email-in tuaj!.
        /// </summary>
        public static string YouMustConfirmEmail {
            get {
                return ResourceManager.GetString("YouMustConfirmEmail", resourceCulture);
            }
        }
    }
}
